@startuml Microservices

title Warmhouse Microservices Device Connector Component Diagram

!include <C4/C4_Component>

Container_Boundary(DepositRepositoryService, "Device Connector Service", "Service", "Handles user interactions and system management") {
    Component(DepositRepositoryAPI, "API Депозитного конвейера", "Работает с заявками. отдаёт текущие ставки")
    Component(ABSEventsListener, "Consumer событий из ABS", "Собирает необходимые данные для ставок")
    Component(DepositEventsPublisher, "Publisher событий Депозитного конвейера", "Публикует одобренные заявки, текущие ставки")
    Component(DepositRatesSFTPExporter, "Коннектор SFTP", "Слушает события по ставкам и периодически сбрасывает в файл по SFTP")
    Component(DepositStorage, "Хранилище заявок на депозит")
    Component(DepositFlowComponent, "Компонент, реализующий flow заявок на депозит")
}

ContainerDb(DepositRepositoryDatabase, "БД с заявками на депозит")

ContainerDb(DepositMessageQueuee, "Kafka DepositConveyor", "Kafka, куда Депозитный конвейер публикует одобренные заявки")

System(CRM, "Система кол-центра","Система кол-центра")

System_Ext(PartnerCRM, "Система партнёрского кол-центра")

@enduml